services:
  - type: worker
    name: koleso-fortuna
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python bot.py
    plan: free
    envVars:
      - key: TOKEN
        sync: false
      - key: CHAT_ID
        sync: false
