services:
  - type: web
    name: Колесо Фортуны от RandomShop🍀
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.13
      - key: PORT
        value: 8000
    autoDeploy: true
